-- GENERATED by scripts/generate-seed.ts from data/hotels.ts. Do not edit by hand.
-- WARNING: total_rooms is a PLACEHOLDER (3 per room type).
-- Set the real room counts in /admin before accepting bookings.
insert into public.room_types (hotel_slug, name, total_rooms, base_rate, max_guests) values
  ('triplicane', 'Deluxe', 3, 899, 2),
  ('triplicane', 'Triple', 3, 1499, 3),
  ('triplicane', 'Quadruple', 3, 1999, 5),
  ('triplicane', 'Suite', 3, 2999, 2),
  ('parrys', 'Standard', 3, 799, 2),
  ('parrys', 'Deluxe', 3, 1499, 4),
  ('koyambedu', 'Deluxe', 3, 899, 2),
  ('koyambedu', 'Deluxe Quad', 3, 1999, 4),
  ('electronic-city', 'Deluxe', 3, 899, 2),
  ('electronic-city', 'Deluxe Twin', 3, 1499, 3),
  ('electronic-city', 'Deluxe Fam', 3, 1999, 4),
  ('koramangala', 'Deluxe Double', 3, 899, 2),
  ('koramangala', 'Deluxe Twin', 3, 1499, 3),
  ('koramangala', 'Junior Suite', 3, 1999, 2),
  ('hyderabad', 'Classic', 3, 899, 2),
  ('hyderabad', 'Deluxe', 3, 1499, 2),
  ('hyderabad', 'Suite', 3, 1999, 2),
  ('ooty', 'Standard', 3, 899, 2),
  ('ooty', 'Deluxe', 3, 1499, 4)
on conflict (hotel_slug, name) do nothing;
