// Generates supabase/seed.sql from data/hotels.ts.
//   npm run seed:sql
// Re-running the seed never overwrites rooms/rates you edited in the database
// (ON CONFLICT DO NOTHING).
import { writeFileSync } from "node:fs";
import { HOTELS } from "../data/hotels";

// PLACEHOLDER inventory: the real number of rooms per room type is not in the
// codebase. Set the real counts in /admin (or here) BEFORE taking bookings.
const PLACEHOLDER_ROOMS_PER_TYPE = 3;

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const rows = HOTELS.flatMap((h) =>
  h.rooms.map(
    (r) =>
      `  (${q(h.slug)}, ${q(r.name)}, ${PLACEHOLDER_ROOMS_PER_TYPE}, ${r.price}, ${r.maxGuests})`
  )
);

const sql = `-- GENERATED by scripts/generate-seed.ts from data/hotels.ts. Do not edit by hand.
-- WARNING: total_rooms is a PLACEHOLDER (${PLACEHOLDER_ROOMS_PER_TYPE} per room type).
-- Set the real room counts in /admin before accepting bookings.
insert into public.room_types (hotel_slug, name, total_rooms, base_rate, max_guests) values
${rows.join(",\n")}
on conflict (hotel_slug, name) do nothing;
`;

writeFileSync("supabase/seed.sql", sql);
console.log(`Wrote supabase/seed.sql (${rows.length} room types)`);
